name: Build
on: [push, pull_request]
jobs:
    build:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
            - name: Install dependencies
              run: npm ci
            - name: ESLint
              run: npm run eslint
            - name: Markdownlint
              run: npm run markdownlint
            - name: Prettier lint
              run: npm run prettier-lint
            - name: Build in production mode
              run: npm run build-production
            - name: Run tests
              run: npm run test
